=== zavx0z/everywhere-everything/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://zavx0z.github.io/node/schema.json#",
  "definitions": {
    "schemaArray": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#/definitions/props" }
    },
    "nonNegativeInteger": {
      "type": "integer",
      "minimum": 0
    },
    "nonNegativeIntegerDefault0": {
      "allOf": [{ "$ref": "#/definitions/nonNegativeInteger" }, { "default": 0 }]
    },
    "simpleTypes": {
      "enum": ["array", "boolean", "integer", "null", "number", "object", "string"]
    },
    "stringArray": {
      "type": "array",
      "items": { "type": "string" },
      "uniqueItems": true,
      "default": []
    },
    "localizedString": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "object",
          "minProperties": 1,
          "propertyNames": {
            "pattern": "^[a-z]{2}(-[A-Z]{2})?$"
          },
          "additionalProperties": {
            "type": "string"
          }
        }
      ]
    },
    "props": {
      "type": "object",
      "properties": {
        "title": {
          "$ref": "#/definitions/localizedString"
        },
        "type": {
          "anyOf": [
            { "$ref": "#/definitions/simpleTypes" },
            {
              "type": "array",
              "items": { "$ref": "#/definitions/simpleTypes" },
              "minItems": 1,
              "uniqueItems": true
            },
            {
              "file": {
                "type": "string",
                "contentMediaType": "application/octet-stream",
                "contentEncoding": "base64"
              }
            }
          ]
        },
        "description": {
          "$ref": "#/definitions/localizedString"
        },
        "examples": {
          "type": "array",
          "items": true
        },
        "pattern": {
          "type": "string",
          "format": "regex"
        }
      },
      "additionalProperties": false
    },
    "params": {
      "type": "object",
      "propertyNames": { "format": "regex" },
      "additionalProperties": {
        "$ref": "#/definitions/props"
      },
      "default": {}
    }
  },
  "properties": {
    "title": {
      "title": "Node Title",
      "$ref": "#/definitions/localizedString"
    },
    "description": {
      "title": "Node description",
      "$ref": "#/definitions/localizedString"
    },
    "preview": {
      "title": "Preview result",
      "type": "boolean"
    },
    "input": {
      "title": "Node input parameters",
      "$ref": "#/definitions/params"
    },
    "output": {
      "title": "Node output parameters",
      "$ref": "#/definitions/params"
    },
    "$schema": {
      "type": "string",
      "format": "uri"
    },
    "position": {
      "type": "object",
      "properties": {
        "x": { "type": "number" },
        "y": { "type": "number" }
      },
      "required": ["x", "y"],
      "additionalProperties": false
    },
    "size": {
      "type": "object",
      "properties": {
        "width": { "type": "number", "minimum": 0 },
        "height": { "type": "number", "minimum": 0 }
      },
      "required": ["width"],
      "additionalProperties": false
    }
  },
  "additionalProperties": false,
  "required": ["$schema", "title"]
}

=== zavx0z/everywhere-everything/example/schema.json
{
  "$schema": "https://zavx0z.github.io/node/schema.json#",
  "title": {
    "en": "Image",
    "ru": "Изображение"
  },
  "description": "Default description without localization",
  "preview": true,
  "input": {
    "filePath": {
      "type": "string",
      "title": {
        "ru": "Путь к изображению"
      },
      "description": {
        "en": "Description with localization",
        "ru": "Описание с локализацией"
      },
      "examples": ["c:\\images\\image.png"],
      "pattern": "^.*\\.(jpg|jpeg|png|gif|bmp)$"
    }
  },
  "output": {
    "base64": {
      "type": "string",
      "title": {
        "ru": "Изображение Base64",
        "en": "Image Base64",
        "de": "Image Base64"
      },
      "description": {
        "ru": "Изображение в формате Base64",
        "en": "Image in Base64 format",
        "de": "Image in Base64 format"
      },
      "examples": ["data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAA"],
      "pattern": "^data:image/.*;base64,.*$"
    }
  }
}

=== zavx0z/everywhere-everything/example/img-base64/schema.json
{
  "$schema": "file:///c:/projects/node/schema.json",
  "title": {
    "en": "Image",
    "ru": "Изображение"
  },
  "description": "Default description without localization",
  "input": {
    "fileImg": {
      "type": "file",
      "title": {
        "ru": "Открыть изображение",
        "en": "Open image"
      },
      "description": {
        "en": "Description with localization",
        "ru": "Описание с локализацией"
      },
      "examples": ["c:\\images\\image.png"],
      "pattern": "^.*\\.(jpg|jpeg|png)$"
    }
  },
  "output": {
    "base64": {
      "type": "string",
      "title": {
        "ru": "Изображение Base64",
        "en": "Image Base64",
        "de": "Image Base64"
      },
      "description": {
        "ru": "Изображение в формате Base64",
        "en": "Image in Base64 format",
        "de": "Image in Base64 format"
      },
      "examples": ["data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAA"],
      "pattern": "^data:image/.*;base64,.*$"
    }
  },
  "position": {
    "x": 10,
    "y": 10
  },
  "size": {
    "width": 100
  },
  "preview": true
}
